//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1022 版自动生成。
// 
#pragma warning disable 1591

namespace JK {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRandom100TiMuStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRandom50TiMuStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZQ_XueXiRiZhiToExamOneOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZQ_XueXiRiZhiToExamThreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTrainingProgressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Properties.Settings.Default.SkinForm_JK_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRandom100TiMuStringCompletedEventHandler GetRandom100TiMuStringCompleted;
        
        /// <remarks/>
        public event GetRandom50TiMuStringCompletedEventHandler GetRandom50TiMuStringCompleted;
        
        /// <remarks/>
        public event ZQ_XueXiRiZhiToExamOneCompletedEventHandler ZQ_XueXiRiZhiToExamOneCompleted;
        
        /// <remarks/>
        public event ZQ_XueXiRiZhiToExamThreeCompletedEventHandler ZQ_XueXiRiZhiToExamThreeCompleted;
        
        /// <remarks/>
        public event GetTrainingProgressCompletedEventHandler GetTrainingProgressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRandom100TiMuString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRandom100TiMuString(string allowDriveCarType) {
            object[] results = this.Invoke("GetRandom100TiMuString", new object[] {
                        allowDriveCarType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRandom100TiMuStringAsync(string allowDriveCarType) {
            this.GetRandom100TiMuStringAsync(allowDriveCarType, null);
        }
        
        /// <remarks/>
        public void GetRandom100TiMuStringAsync(string allowDriveCarType, object userState) {
            if ((this.GetRandom100TiMuStringOperationCompleted == null)) {
                this.GetRandom100TiMuStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRandom100TiMuStringOperationCompleted);
            }
            this.InvokeAsync("GetRandom100TiMuString", new object[] {
                        allowDriveCarType}, this.GetRandom100TiMuStringOperationCompleted, userState);
        }
        
        private void OnGetRandom100TiMuStringOperationCompleted(object arg) {
            if ((this.GetRandom100TiMuStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRandom100TiMuStringCompleted(this, new GetRandom100TiMuStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRandom50TiMuString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRandom50TiMuString() {
            object[] results = this.Invoke("GetRandom50TiMuString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRandom50TiMuStringAsync() {
            this.GetRandom50TiMuStringAsync(null);
        }
        
        /// <remarks/>
        public void GetRandom50TiMuStringAsync(object userState) {
            if ((this.GetRandom50TiMuStringOperationCompleted == null)) {
                this.GetRandom50TiMuStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRandom50TiMuStringOperationCompleted);
            }
            this.InvokeAsync("GetRandom50TiMuString", new object[0], this.GetRandom50TiMuStringOperationCompleted, userState);
        }
        
        private void OnGetRandom50TiMuStringOperationCompleted(object arg) {
            if ((this.GetRandom50TiMuStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRandom50TiMuStringCompleted(this, new GetRandom50TiMuStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ZQ_XueXiRiZhiToExamOne", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ZQ_XueXiRiZhiToExamOne(int XueYuanLiuShuiHao, string BeiZhu) {
            object[] results = this.Invoke("ZQ_XueXiRiZhiToExamOne", new object[] {
                        XueYuanLiuShuiHao,
                        BeiZhu});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ZQ_XueXiRiZhiToExamOneAsync(int XueYuanLiuShuiHao, string BeiZhu) {
            this.ZQ_XueXiRiZhiToExamOneAsync(XueYuanLiuShuiHao, BeiZhu, null);
        }
        
        /// <remarks/>
        public void ZQ_XueXiRiZhiToExamOneAsync(int XueYuanLiuShuiHao, string BeiZhu, object userState) {
            if ((this.ZQ_XueXiRiZhiToExamOneOperationCompleted == null)) {
                this.ZQ_XueXiRiZhiToExamOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZQ_XueXiRiZhiToExamOneOperationCompleted);
            }
            this.InvokeAsync("ZQ_XueXiRiZhiToExamOne", new object[] {
                        XueYuanLiuShuiHao,
                        BeiZhu}, this.ZQ_XueXiRiZhiToExamOneOperationCompleted, userState);
        }
        
        private void OnZQ_XueXiRiZhiToExamOneOperationCompleted(object arg) {
            if ((this.ZQ_XueXiRiZhiToExamOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZQ_XueXiRiZhiToExamOneCompleted(this, new ZQ_XueXiRiZhiToExamOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ZQ_XueXiRiZhiToExamThree", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ZQ_XueXiRiZhiToExamThree(int XueYuanLiuShuiHao, string BeiZhu) {
            object[] results = this.Invoke("ZQ_XueXiRiZhiToExamThree", new object[] {
                        XueYuanLiuShuiHao,
                        BeiZhu});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ZQ_XueXiRiZhiToExamThreeAsync(int XueYuanLiuShuiHao, string BeiZhu) {
            this.ZQ_XueXiRiZhiToExamThreeAsync(XueYuanLiuShuiHao, BeiZhu, null);
        }
        
        /// <remarks/>
        public void ZQ_XueXiRiZhiToExamThreeAsync(int XueYuanLiuShuiHao, string BeiZhu, object userState) {
            if ((this.ZQ_XueXiRiZhiToExamThreeOperationCompleted == null)) {
                this.ZQ_XueXiRiZhiToExamThreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZQ_XueXiRiZhiToExamThreeOperationCompleted);
            }
            this.InvokeAsync("ZQ_XueXiRiZhiToExamThree", new object[] {
                        XueYuanLiuShuiHao,
                        BeiZhu}, this.ZQ_XueXiRiZhiToExamThreeOperationCompleted, userState);
        }
        
        private void OnZQ_XueXiRiZhiToExamThreeOperationCompleted(object arg) {
            if ((this.ZQ_XueXiRiZhiToExamThreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZQ_XueXiRiZhiToExamThreeCompleted(this, new ZQ_XueXiRiZhiToExamThreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTrainingProgress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTrainingProgress(string xuehao, int subject) {
            object[] results = this.Invoke("GetTrainingProgress", new object[] {
                        xuehao,
                        subject});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTrainingProgressAsync(string xuehao, int subject) {
            this.GetTrainingProgressAsync(xuehao, subject, null);
        }
        
        /// <remarks/>
        public void GetTrainingProgressAsync(string xuehao, int subject, object userState) {
            if ((this.GetTrainingProgressOperationCompleted == null)) {
                this.GetTrainingProgressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTrainingProgressOperationCompleted);
            }
            this.InvokeAsync("GetTrainingProgress", new object[] {
                        xuehao,
                        subject}, this.GetTrainingProgressOperationCompleted, userState);
        }
        
        private void OnGetTrainingProgressOperationCompleted(object arg) {
            if ((this.GetTrainingProgressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTrainingProgressCompleted(this, new GetTrainingProgressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRandom100TiMuStringCompletedEventHandler(object sender, GetRandom100TiMuStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRandom100TiMuStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRandom100TiMuStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRandom50TiMuStringCompletedEventHandler(object sender, GetRandom50TiMuStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRandom50TiMuStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRandom50TiMuStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ZQ_XueXiRiZhiToExamOneCompletedEventHandler(object sender, ZQ_XueXiRiZhiToExamOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZQ_XueXiRiZhiToExamOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZQ_XueXiRiZhiToExamOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ZQ_XueXiRiZhiToExamThreeCompletedEventHandler(object sender, ZQ_XueXiRiZhiToExamThreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZQ_XueXiRiZhiToExamThreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZQ_XueXiRiZhiToExamThreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTrainingProgressCompletedEventHandler(object sender, GetTrainingProgressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTrainingProgressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTrainingProgressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591