//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoukeyNetget.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class globalUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal globalUI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoukeyNetget.Resources.globalUI", typeof(globalUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 上午 的本地化字符串。
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入网址信息 的本地化字符串。
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入采集数据的结束标志 的本地化字符串。
        /// </summary>
        internal static string Error10 {
            get {
                return ResourceManager.GetString("Error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集的名称不能重复，请重新命名 的本地化字符串。
        /// </summary>
        internal static string Error11 {
            get {
                return ResourceManager.GetString("Error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接发生错误，错误信息： 的本地化字符串。
        /// </summary>
        internal static string Error12 {
            get {
                return ResourceManager.GetString("Error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务保存时失败，出错原因是： 的本地化字符串。
        /// </summary>
        internal static string Error13 {
            get {
                return ResourceManager.GetString("Error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘分类文件遭到破坏，无法加载，请拷贝安装文件中“TaskClass.xml”文件到系统根目录修复此任务！ 的本地化字符串。
        /// </summary>
        internal static string Error14 {
            get {
                return ResourceManager.GetString("Error14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载运行任务出错，首先删除正在运行的任务，退出系统后，进入系统所在目录中的Tasks下，删除taskrun.xml，重启即可！错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Error15 {
            get {
                return ResourceManager.GetString("Error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载的任务运行监控:taskrun.xml 文件非法，请检查此文件，或将其删除，并重新点击此节点由系统自动建立！ 的本地化字符串。
        /// </summary>
        internal static string Error16 {
            get {
                return ResourceManager.GetString("Error16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所拷贝的任务分类路径不存在！ 的本地化字符串。
        /// </summary>
        internal static string Error17 {
            get {
                return ResourceManager.GetString("Error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划名称不能为空! 的本地化字符串。
        /// </summary>
        internal static string Error18 {
            get {
                return ResourceManager.GetString("Error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少应该有一任务被执行 的本地化字符串。
        /// </summary>
        internal static string Error19 {
            get {
                return ResourceManager.GetString("Error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的网址不合法，请检查 的本地化字符串。
        /// </summary>
        internal static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果您选择了计划1次便失效，则必须选择执行计划中的仅“运行一次”选项 的本地化字符串。
        /// </summary>
        internal static string Error20 {
            get {
                return ResourceManager.GetString("Error20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存任务发生了错误，初步判断原因是系统错误，请与一孑工作室联系！ 的本地化字符串。
        /// </summary>
        internal static string Error21 {
            get {
                return ResourceManager.GetString("Error21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务名称不能为空! 的本地化字符串。
        /// </summary>
        internal static string Error22 {
            get {
                return ResourceManager.GetString("Error22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载正在运行的任务出错，发生错误的任务将无法显示在运行区，有可能是由于这些任务引用了不存在的字典参数，建议修复丢失的字典参数，如果错误还是无法解决，请在运行区所有任务都运行完毕后，删除Tasks\taskrun.xml文件，通过程序自动建立此文件，从而修复此问题。 的本地化字符串。
        /// </summary>
        internal static string Error23 {
            get {
                return ResourceManager.GetString("Error23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少需要提供一个需要采集数据的网址！ 的本地化字符串。
        /// </summary>
        internal static string Error24 {
            get {
                return ResourceManager.GetString("Error24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少需要提供一种采集数据的规则！ 的本地化字符串。
        /// </summary>
        internal static string Error25 {
            get {
                return ResourceManager.GetString("Error25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航规则配置错误，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Error26 {
            get {
                return ResourceManager.GetString("Error26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务保存时失败，出错原因是： 的本地化字符串。
        /// </summary>
        internal static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集发生错误，错误信息： 的本地化字符串。
        /// </summary>
        internal static string Error4 {
            get {
                return ResourceManager.GetString("Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航规则为空，无法测试！ 的本地化字符串。
        /// </summary>
        internal static string Error5 {
            get {
                return ResourceManager.GetString("Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址无法打开，可能出错，请检查网址及导航规则。 的本地化字符串。
        /// </summary>
        internal static string Error6 {
            get {
                return ResourceManager.GetString("Error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取网页源代码出错，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Error7 {
            get {
                return ResourceManager.GetString("Error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入采集数据的名称 的本地化字符串。
        /// </summary>
        internal static string Error8 {
            get {
                return ResourceManager.GetString("Error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入采集数据的起始标志 的本地化字符串。
        /// </summary>
        internal static string Error9 {
            get {
                return ResourceManager.GetString("Error9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每天 的本地化字符串。
        /// </summary>
        internal static string Everyday {
            get {
                return ResourceManager.GetString("Everyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已采数量 的本地化字符串。
        /// </summary>
        internal static string GridCollectionCount {
            get {
                return ResourceManager.GetString("GridCollectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成数量 的本地化字符串。
        /// </summary>
        internal static string GridCompleteCount {
            get {
                return ResourceManager.GetString("GridCompleteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        internal static string GridCount {
            get {
                return ResourceManager.GetString("GridCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误数量 的本地化字符串。
        /// </summary>
        internal static string GridErrorCount {
            get {
                return ResourceManager.GetString("GridErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导出数量 的本地化字符串。
        /// </summary>
        internal static string GridExportedCount {
            get {
                return ResourceManager.GetString("GridExportedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出类型 的本地化字符串。
        /// </summary>
        internal static string GridExportType {
            get {
                return ResourceManager.GetString("GridExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string GridID {
            get {
                return ResourceManager.GetString("GridID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否登录 的本地化字符串。
        /// </summary>
        internal static string GridIsLogon {
            get {
                return ResourceManager.GetString("GridIsLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否过期 的本地化字符串。
        /// </summary>
        internal static string GridIsOvertime {
            get {
                return ResourceManager.GetString("GridIsOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下次执行时间 的本地化字符串。
        /// </summary>
        internal static string GridNextTime {
            get {
                return ResourceManager.GetString("GridNextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期规则 的本地化字符串。
        /// </summary>
        internal static string GridOvertimeRule {
            get {
                return ResourceManager.GetString("GridOvertimeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        internal static string GridPara {
            get {
                return ResourceManager.GetString("GridPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划名称 的本地化字符串。
        /// </summary>
        internal static string GridPlanName {
            get {
                return ResourceManager.GetString("GridPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度 的本地化字符串。
        /// </summary>
        internal static string GridProcess {
            get {
                return ResourceManager.GetString("GridProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已导出 的本地化字符串。
        /// </summary>
        internal static string GridPublished {
            get {
                return ResourceManager.GetString("GridPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string GridRemark {
            get {
                return ResourceManager.GetString("GridRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行计划 的本地化字符串。
        /// </summary>
        internal static string GridRunPlan {
            get {
                return ResourceManager.GetString("GridRunPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行时间 的本地化字符串。
        /// </summary>
        internal static string GridRunTime {
            get {
                return ResourceManager.GetString("GridRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string GridState {
            get {
                return ResourceManager.GetString("GridState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务编号 的本地化字符串。
        /// </summary>
        internal static string GridTaskID {
            get {
                return ResourceManager.GetString("GridTaskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务名称 的本地化字符串。
        /// </summary>
        internal static string GridTaskName {
            get {
                return ResourceManager.GetString("GridTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行类型 的本地化字符串。
        /// </summary>
        internal static string GridTaskRunType {
            get {
                return ResourceManager.GetString("GridTaskRunType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string GridTaskState {
            get {
                return ResourceManager.GetString("GridTaskState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务类型 的本地化字符串。
        /// </summary>
        internal static string GridTaskType {
            get {
                return ResourceManager.GetString("GridTaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集网址数量 的本地化字符串。
        /// </summary>
        internal static string GridUrlCount {
            get {
                return ResourceManager.GetString("GridUrlCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您加载的任务与当前系统支持的任务版本不同，请升级任务版本后再进行加载 的本地化字符串。
        /// </summary>
        internal static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止计划监听服务失败，失败信息为： 的本地化字符串。
        /// </summary>
        internal static string Info10 {
            get {
                return ResourceManager.GetString("Info10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载成功，请在Soukey采摘工作目录中检查Soukey.exe文件，此文件为最新版本，并且是rar自解压的免安装版本！ 的本地化字符串。
        /// </summary>
        internal static string Info100 {
            get {
                return ResourceManager.GetString("Info100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新失败！错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info101 {
            get {
                return ResourceManager.GetString("Info101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载最新版本，请等待...... 的本地化字符串。
        /// </summary>
        internal static string Info102 {
            get {
                return ResourceManager.GetString("Info102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找到待升级任务： 的本地化字符串。
        /// </summary>
        internal static string Info103 {
            get {
                return ResourceManager.GetString("Info103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在查找... 的本地化字符串。
        /// </summary>
        internal static string Info104 {
            get {
                return ResourceManager.GetString("Info104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定需要导入任务的文件名 的本地化字符串。
        /// </summary>
        internal static string Info105 {
            get {
                return ResourceManager.GetString("Info105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此任务版本为最新，无需升级！ 的本地化字符串。
        /// </summary>
        internal static string Info106 {
            get {
                return ResourceManager.GetString("Info106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增待升级任务发生错误，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info107 {
            get {
                return ResourceManager.GetString("Info107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有待升级的任务 的本地化字符串。
        /// </summary>
        internal static string Info108 {
            get {
                return ResourceManager.GetString("Info108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在升级 的本地化字符串。
        /// </summary>
        internal static string Info109 {
            get {
                return ResourceManager.GetString("Info109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此任务执行需要获取Cookie，但您取消了Cookie获取操作，任务被迫中断！ 的本地化字符串。
        /// </summary>
        internal static string Info11 {
            get {
                return ResourceManager.GetString("Info11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级成功 的本地化字符串。
        /// </summary>
        internal static string Info110 {
            get {
                return ResourceManager.GetString("Info110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级失败 的本地化字符串。
        /// </summary>
        internal static string Info111 {
            get {
                return ResourceManager.GetString("Info111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有可能任务已经已被破坏，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info112 {
            get {
                return ResourceManager.GetString("Info112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的修改已经成功，但需要在下次系统启动时才会生效！ 的本地化字符串。
        /// </summary>
        internal static string Info113 {
            get {
                return ResourceManager.GetString("Info113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先填写网址，再进行导航规则的添加 的本地化字符串。
        /// </summary>
        internal static string Info114 {
            get {
                return ResourceManager.GetString("Info114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航前缀只能添加一次，且只能第一次添加 的本地化字符串。
        /// </summary>
        internal static string Info115 {
            get {
                return ResourceManager.GetString("Info115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先添加导航网址的前缀，才可添加公共部分 的本地化字符串。
        /// </summary>
        internal static string Info116 {
            get {
                return ResourceManager.GetString("Info116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解析导航网址，请等待...... 的本地化字符串。
        /// </summary>
        internal static string Info117 {
            get {
                return ResourceManager.GetString("Info117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定导出的文本文件名 的本地化字符串。
        /// </summary>
        internal static string Info12 {
            get {
                return ResourceManager.GetString("Info12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定导出的Excel文件名 的本地化字符串。
        /// </summary>
        internal static string Info13 {
            get {
                return ResourceManager.GetString("Info13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败，文件可能受到破坏，请删除后重新建立！ 的本地化字符串。
        /// </summary>
        internal static string Info14 {
            get {
                return ResourceManager.GetString("Info14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始于 的本地化字符串。
        /// </summary>
        internal static string Info15 {
            get {
                return ResourceManager.GetString("Info15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔 的本地化字符串。
        /// </summary>
        internal static string Info16 {
            get {
                return ResourceManager.GetString("Info16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过 的本地化字符串。
        /// </summary>
        internal static string Info17 {
            get {
                return ResourceManager.GetString("Info17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永不失效 的本地化字符串。
        /// </summary>
        internal static string Info18 {
            get {
                return ResourceManager.GetString("Info18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您加载的任务与当前系统支持的任务版本不同，操作建议：删除此任务运行实例，升级此任务再次运行即可！ 的本地化字符串。
        /// </summary>
        internal static string Info19 {
            get {
                return ResourceManager.GetString("Info19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储路径 的本地化字符串。
        /// </summary>
        internal static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除系统分类： 的本地化字符串。
        /// </summary>
        internal static string Info20 {
            get {
                return ResourceManager.GetString("Info20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择删除分类： 的本地化字符串。
        /// </summary>
        internal static string Info21 {
            get {
                return ResourceManager.GetString("Info21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除分类将同时删除此分类下的所有任务，您是否继续执行删除操作? 的本地化字符串。
        /// </summary>
        internal static string Info22 {
            get {
                return ResourceManager.GetString("Info22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除分类发生错误，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info23 {
            get {
                return ResourceManager.GetString("Info23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认删除计划任务： 的本地化字符串。
        /// </summary>
        internal static string Info24 {
            get {
                return ResourceManager.GetString("Info24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除后此计划不可恢复，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Info25 {
            get {
                return ResourceManager.GetString("Info25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择了删除多个计划任务，删除后计划将不可恢复，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Info26 {
            get {
                return ResourceManager.GetString("Info26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除计划时出错，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info27 {
            get {
                return ResourceManager.GetString("Info27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择删除任务： 的本地化字符串。
        /// </summary>
        internal static string Info28 {
            get {
                return ResourceManager.GetString("Info28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认删除任务： 的本地化字符串。
        /// </summary>
        internal static string Info29 {
            get {
                return ResourceManager.GetString("Info29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此任务没有定义需要采集的网址，无法进行采集测试工作！ 的本地化字符串。
        /// </summary>
        internal static string Info3 {
            get {
                return ResourceManager.GetString("Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您指定的计划不存在，或者计划信息被非法破坏，请删除此计划后重建，或直接修改计划xml文件予以修复！错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info30 {
            get {
                return ResourceManager.GetString("Info30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您指定打开的任务不存在，可能已被删除！通常情况下，系统会建立此任务的备份，您可通过导入功能导入此任务。 的本地化字符串。
        /// </summary>
        internal static string Info31 {
            get {
                return ResourceManager.GetString("Info31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您加载的任务出错，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info32 {
            get {
                return ResourceManager.GetString("Info32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通常情况下，系统会建立此任务的备份，您可通过导入功能导入此任务。 的本地化字符串。
        /// </summary>
        internal static string Info33 {
            get {
                return ResourceManager.GetString("Info33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前任务正在运行，无法关闭此任务的数据输出窗口！ 的本地化字符串。
        /// </summary>
        internal static string Info34 {
            get {
                return ResourceManager.GetString("Info34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经有手动导出任务正在运行，请等待此任务运行完成后，再进行手动数据导出！ 的本地化字符串。
        /// </summary>
        internal static string Info35 {
            get {
                return ResourceManager.GetString("Info35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定存储数据的文件名 的本地化字符串。
        /// </summary>
        internal static string Info36 {
            get {
                return ResourceManager.GetString("Info36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动导出数据 的本地化字符串。
        /// </summary>
        internal static string Info37 {
            get {
                return ResourceManager.GetString("Info37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出数据已经开始 的本地化字符串。
        /// </summary>
        internal static string Info38 {
            get {
                return ResourceManager.GetString("Info38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出数据已经完成 的本地化字符串。
        /// </summary>
        internal static string Info39 {
            get {
                return ResourceManager.GetString("Info39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此任务没有定义需要采集数据的采集规则，无法进行采集测试工作！ 的本地化字符串。
        /// </summary>
        internal static string Info4 {
            get {
                return ResourceManager.GetString("Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置文件加载失败，可从安装文件中拷贝文件：SoukeyConfig.xml 到Soukey采摘安装目录，配置文件损坏并不影响系统运行，但您做的系统配置可能无法保存！ 的本地化字符串。
        /// </summary>
        internal static string Info40 {
            get {
                return ResourceManager.GetString("Info40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择了重置任务： 的本地化字符串。
        /// </summary>
        internal static string Info41 {
            get {
                return ResourceManager.GetString("Info41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务重置出错： 的本地化字符串。
        /// </summary>
        internal static string Info42 {
            get {
                return ResourceManager.GetString("Info42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务在加载临时采集数据时发生错误，有可能是由于权限受限或强制退出所导致！ 的本地化字符串。
        /// </summary>
        internal static string Info43 {
            get {
                return ResourceManager.GetString("Info43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定需要导入任务的文件名 的本地化字符串。
        /// </summary>
        internal static string Info44 {
            get {
                return ResourceManager.GetString("Info44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您导入的任务已经存在，请选择其他需要导入的任务！ 的本地化字符串。
        /// </summary>
        internal static string Info45 {
            get {
                return ResourceManager.GetString("Info45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您指定的任务已经存在，但您可能无法通过Soukey采摘看到，是因为您曾经删除了此任务，但任务文件还存在，可通过修改此文件名后再进行任务导入操作！ 的本地化字符串。
        /// </summary>
        internal static string Info46 {
            get {
                return ResourceManager.GetString("Info46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您指定的任务已成功导入，所属分类： 的本地化字符串。
        /// </summary>
        internal static string Info47 {
            get {
                return ResourceManager.GetString("Info47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败，错误信息： 的本地化字符串。
        /// </summary>
        internal static string Info48 {
            get {
                return ResourceManager.GetString("Info48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改任务分类发生错误，错误信息： 的本地化字符串。
        /// </summary>
        internal static string Info49 {
            get {
                return ResourceManager.GetString("Info49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在进行数据采集，请等待...... 的本地化字符串。
        /// </summary>
        internal static string Info5 {
            get {
                return ResourceManager.GetString("Info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能把任务拖放到： 的本地化字符串。
        /// </summary>
        internal static string Info50 {
            get {
                return ResourceManager.GetString("Info50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志保存失败： 的本地化字符串。
        /// </summary>
        internal static string Info51 {
            get {
                return ResourceManager.GetString("Info51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭“系统信息” 的本地化字符串。
        /// </summary>
        internal static string Info52 {
            get {
                return ResourceManager.GetString("Info52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘 任务选项 的本地化字符串。
        /// </summary>
        internal static string Info53 {
            get {
                return ResourceManager.GetString("Info53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载的任务运行监控文件非法，请通过Windows文件浏览器删除，并重新点击此节点由系统自动建立！文件： 的本地化字符串。
        /// </summary>
        internal static string Info54 {
            get {
                return ResourceManager.GetString("Info54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载的已完成任务索引文件非法，请通过Windows文件浏览器删除，并重新点击此节点由系统自动建立！文件: 的本地化字符串。
        /// </summary>
        internal static string Info55 {
            get {
                return ResourceManager.GetString("Info55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载系统任务出错，系统认为为：Soukey采摘 最新版本下载。 的本地化字符串。
        /// </summary>
        internal static string Info56 {
            get {
                return ResourceManager.GetString("Info56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载任务执行计划出错，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info57 {
            get {
                return ResourceManager.GetString("Info57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载任务执行计划日志出错，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info58 {
            get {
                return ResourceManager.GetString("Info58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载任务执行计划日志出错，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info59 {
            get {
                return ResourceManager.GetString("Info59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请首先获取示例网址，再进行源代码查看！ 的本地化字符串。
        /// </summary>
        internal static string Info6 {
            get {
                return ResourceManager.GetString("Info6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定存储采集日志文件的名称 的本地化字符串。
        /// </summary>
        internal static string Info60 {
            get {
                return ResourceManager.GetString("Info60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置文件操作失败，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info61 {
            get {
                return ResourceManager.GetString("Info61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在修改任务分类的名称，请稍等...... 的本地化字符串。
        /// </summary>
        internal static string Info62 {
            get {
                return ResourceManager.GetString("Info62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改任务分类名称发生错误，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info63 {
            get {
                return ResourceManager.GetString("Info63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改任务名称发生错误，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info64 {
            get {
                return ResourceManager.GetString("Info64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改计划名称发生错误，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info65 {
            get {
                return ResourceManager.GetString("Info65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在修改计划的名称，请稍等...... 的本地化字符串。
        /// </summary>
        internal static string Info66 {
            get {
                return ResourceManager.GetString("Info66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在修改任务的名称，请稍等...... 的本地化字符串。
        /// </summary>
        internal static string Info67 {
            get {
                return ResourceManager.GetString("Info67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务拷贝失败，错误信息： 的本地化字符串。
        /// </summary>
        internal static string Info68 {
            get {
                return ResourceManager.GetString("Info68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化主程序应用信息，请等待...... 的本地化字符串。
        /// </summary>
        internal static string Info69 {
            get {
                return ResourceManager.GetString("Info69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择采集任务数据存储的路径： 的本地化字符串。
        /// </summary>
        internal static string Info7 {
            get {
                return ResourceManager.GetString("Info7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化任务信息并开始启动运行区的任务，请等待...... 的本地化字符串。
        /// </summary>
        internal static string Info70 {
            get {
                return ResourceManager.GetString("Info70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动自动运行任务监听器，请等待...... 的本地化字符串。
        /// </summary>
        internal static string Info71 {
            get {
                return ResourceManager.GetString("Info71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类下的索引文件丢失，请返回主界面通过点击丢失文件的任务分类自动创建 的本地化字符串。
        /// </summary>
        internal static string Info72 {
            get {
                return ResourceManager.GetString("Info72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载的任务分类索引文件非法，请返回主界面通过点击此任务分类校验文件是否合法。 的本地化字符串。
        /// </summary>
        internal static string Info73 {
            get {
                return ResourceManager.GetString("Info73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要运行的程序或脚本 的本地化字符串。
        /// </summary>
        internal static string Info74 {
            get {
                return ResourceManager.GetString("Info74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接发生错误，错误信息： 的本地化字符串。
        /// </summary>
        internal static string Info75 {
            get {
                return ResourceManager.GetString("Info75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置文件加载失败，可从安装文件中拷贝文件：SoukeyConfig.xml 到Soukey采摘安装目录，配置文件损坏并不影响系统运行，但您做的系统配置可能无法保存！ 的本地化字符串。
        /// </summary>
        internal static string Info76 {
            get {
                return ResourceManager.GetString("Info76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择字典分类再进行字典内容的添加 的本地化字符串。
        /// </summary>
        internal static string Info77 {
            get {
                return ResourceManager.GetString("Info77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改字典名称出错，错误信息为： 的本地化字符串。
        /// </summary>
        internal static string Info78 {
            get {
                return ResourceManager.GetString("Info78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根节点无法删除！ 的本地化字符串。
        /// </summary>
        internal static string Info79 {
            get {
                return ResourceManager.GetString("Info79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写导航规则后再添加 的本地化字符串。
        /// </summary>
        internal static string Info8 {
            get {
                return ResourceManager.GetString("Info8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无删除的字典内容或为选中删除的内容！ 的本地化字符串。
        /// </summary>
        internal static string Info80 {
            get {
                return ResourceManager.GetString("Info80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动响应： 的本地化字符串。
        /// </summary>
        internal static string Info81 {
            get {
                return ResourceManager.GetString("Info81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统默认选择为“是(Y)” 的本地化字符串。
        /// </summary>
        internal static string Info82 {
            get {
                return ResourceManager.GetString("Info82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择任务分类筛选任务，如果放弃操作，请点击“取消” 的本地化字符串。
        /// </summary>
        internal static string Info83 {
            get {
                return ResourceManager.GetString("Info83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定Access数据库文件 的本地化字符串。
        /// </summary>
        internal static string Info84 {
            get {
                return ResourceManager.GetString("Info84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要发布的MSSqlServer数据库名称！ 的本地化字符串。
        /// </summary>
        internal static string Info85 {
            get {
                return ResourceManager.GetString("Info85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要发布的MySql数据库名称！ 的本地化字符串。
        /// </summary>
        internal static string Info86 {
            get {
                return ResourceManager.GetString("Info86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库链接成功！ 的本地化字符串。
        /// </summary>
        internal static string Info87 {
            get {
                return ResourceManager.GetString("Info87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务分类名称需要填写 的本地化字符串。
        /// </summary>
        internal static string Info88 {
            get {
                return ResourceManager.GetString("Info88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划保存时失败，出错原因是： 的本地化字符串。
        /// </summary>
        internal static string Info89 {
            get {
                return ResourceManager.GetString("Info89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动计划监听服务失败，失败信息为： 的本地化字符串。
        /// </summary>
        internal static string Info9 {
            get {
                return ResourceManager.GetString("Info9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在获取本地系统版本号........ 的本地化字符串。
        /// </summary>
        internal static string Info90 {
            get {
                return ResourceManager.GetString("Info90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地版本号为： 的本地化字符串。
        /// </summary>
        internal static string Info91 {
            get {
                return ResourceManager.GetString("Info91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始连接Soukey采摘官方网站：http://www.yijie.net ...... 的本地化字符串。
        /// </summary>
        internal static string Info92 {
            get {
                return ResourceManager.GetString("Info92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败，请确认是否已经连接到Internet。 的本地化字符串。
        /// </summary>
        internal static string Info93 {
            get {
                return ResourceManager.GetString("Info93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查已经停止！ 的本地化字符串。
        /// </summary>
        internal static string Info94 {
            get {
                return ResourceManager.GetString("Info94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接成功！ 的本地化字符串。
        /// </summary>
        internal static string Info95 {
            get {
                return ResourceManager.GetString("Info95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始获取Soukey采摘最新版本号....... 的本地化字符串。
        /// </summary>
        internal static string Info96 {
            get {
                return ResourceManager.GetString("Info96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘最新版本号为： 的本地化字符串。
        /// </summary>
        internal static string Info97 {
            get {
                return ResourceManager.GetString("Info97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现了新的版本，版本说明如下： 的本地化字符串。
        /// </summary>
        internal static string Info98 {
            get {
                return ResourceManager.GetString("Info98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有新版本，无需进行下载操作！ 的本地化字符串。
        /// </summary>
        internal static string Info99 {
            get {
                return ResourceManager.GetString("Info99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统启动 的本地化字符串。
        /// </summary>
        internal static string InfoStart {
            get {
                return ResourceManager.GetString("InfoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工条件： 的本地化字符串。
        /// </summary>
        internal static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务失败 的本地化字符串。
        /// </summary>
        internal static string Label10 {
            get {
                return ResourceManager.GetString("Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务暂停 的本地化字符串。
        /// </summary>
        internal static string Label11 {
            get {
                return ResourceManager.GetString("Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务正在运行 的本地化字符串。
        /// </summary>
        internal static string Label12 {
            get {
                return ResourceManager.GetString("Label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务正在运行 的本地化字符串。
        /// </summary>
        internal static string Label13 {
            get {
                return ResourceManager.GetString("Label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务等待运行 的本地化字符串。
        /// </summary>
        internal static string Label14 {
            get {
                return ResourceManager.GetString("Label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务正在发布 的本地化字符串。
        /// </summary>
        internal static string Label15 {
            get {
                return ResourceManager.GetString("Label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘任务 的本地化字符串。
        /// </summary>
        internal static string Label16 {
            get {
                return ResourceManager.GetString("Label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他任务 的本地化字符串。
        /// </summary>
        internal static string Label17 {
            get {
                return ResourceManager.GetString("Label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库任务 的本地化字符串。
        /// </summary>
        internal static string Label18 {
            get {
                return ResourceManager.GetString("Label18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建字典分类 的本地化字符串。
        /// </summary>
        internal static string Label19 {
            get {
                return ResourceManager.GetString("Label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前缀： 的本地化字符串。
        /// </summary>
        internal static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建字典内容 的本地化字符串。
        /// </summary>
        internal static string Label20 {
            get {
                return ResourceManager.GetString("Label20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string Label21 {
            get {
                return ResourceManager.GetString("Label21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        internal static string Label22 {
            get {
                return ResourceManager.GetString("Label22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        internal static string Label23 {
            get {
                return ResourceManager.GetString("Label23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检测 的本地化字符串。
        /// </summary>
        internal static string Label24 {
            get {
                return ResourceManager.GetString("Label24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string Label25 {
            get {
                return ResourceManager.GetString("Label25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文简体 的本地化字符串。
        /// </summary>
        internal static string Label26 {
            get {
                return ResourceManager.GetString("Label26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string Label27 {
            get {
                return ResourceManager.GetString("Label27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string Label28 {
            get {
                return ResourceManager.GetString("Label28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Label29 {
            get {
                return ResourceManager.GetString("Label29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后缀： 的本地化字符串。
        /// </summary>
        internal static string Label3 {
            get {
                return ResourceManager.GetString("Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保  存 的本地化字符串。
        /// </summary>
        internal static string Label30 {
            get {
                return ResourceManager.GetString("Label30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此任务不分类，直接保存到默认路径 的本地化字符串。
        /// </summary>
        internal static string Label31 {
            get {
                return ResourceManager.GetString("Label31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航网址前缀 的本地化字符串。
        /// </summary>
        internal static string Label32 {
            get {
                return ResourceManager.GetString("Label32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相同部分 的本地化字符串。
        /// </summary>
        internal static string Label33 {
            get {
                return ResourceManager.GetString("Label33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航网址后缀 的本地化字符串。
        /// </summary>
        internal static string Label34 {
            get {
                return ResourceManager.GetString("Label34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截取字符数： 的本地化字符串。
        /// </summary>
        internal static string Label4 {
            get {
                return ResourceManager.GetString("Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式： 的本地化字符串。
        /// </summary>
        internal static string Label5 {
            get {
                return ResourceManager.GetString("Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则表达式： 的本地化字符串。
        /// </summary>
        internal static string Label6 {
            get {
                return ResourceManager.GetString("Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务未启动 的本地化字符串。
        /// </summary>
        internal static string Label7 {
            get {
                return ResourceManager.GetString("Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务已停止 的本地化字符串。
        /// </summary>
        internal static string Label8 {
            get {
                return ResourceManager.GetString("Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务已完成 的本地化字符串。
        /// </summary>
        internal static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志保存 的本地化字符串。
        /// </summary>
        internal static string LogSave {
            get {
                return ResourceManager.GetString("LogSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志保存成功 的本地化字符串。
        /// </summary>
        internal static string LogSaveSuccess {
            get {
                return ResourceManager.GetString("LogSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘 系统错误 的本地化字符串。
        /// </summary>
        internal static string MessageboxError {
            get {
                return ResourceManager.GetString("MessageboxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘 系统信息 的本地化字符串。
        /// </summary>
        internal static string MessageboxInfo {
            get {
                return ResourceManager.GetString("MessageboxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘 系统询问 的本地化字符串。
        /// </summary>
        internal static string MessageboxQuaere {
            get {
                return ResourceManager.GetString("MessageboxQuaere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘 系统警告 的本地化字符串。
        /// </summary>
        internal static string MessageboxWarning {
            get {
                return ResourceManager.GetString("MessageboxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 级别 的本地化字符串。
        /// </summary>
        internal static string NaviLevel {
            get {
                return ResourceManager.GetString("NaviLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集规则 的本地化字符串。
        /// </summary>
        internal static string NaviRule {
            get {
                return ResourceManager.GetString("NaviRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不登录 的本地化字符串。
        /// </summary>
        internal static string NoLogon {
            get {
                return ResourceManager.GetString("NoLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下午 的本地化字符串。
        /// </summary>
        internal static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此任务没有定义需要采集的网址或者采集网址的规则，是否继续保存任务？ 的本地化字符串。
        /// </summary>
        internal static string Quaere1 {
            get {
                return ResourceManager.GetString("Quaere1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除已经完成的任务将会删除已经采集的数据，您可在删除任务前导出数据，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere10 {
            get {
                return ResourceManager.GetString("Quaere10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择了删除多个已完成的任务，删除已经完成的任务将会删除已经采集的数据，您可在删除任务前导出数据，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere11 {
            get {
                return ResourceManager.GetString("Quaere11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择启动的任务已经在运行区存在或者有相同名称的任务已经在运行区，您是否确认此任务需要运行或需要此任务运行第二个实例？ 的本地化字符串。
        /// </summary>
        internal static string Quaere12 {
            get {
                return ResourceManager.GetString("Quaere12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前任务已经加载到运行区无法进行修改操作，继续查看？ 的本地化字符串。
        /// </summary>
        internal static string Quaere13 {
            get {
                return ResourceManager.GetString("Quaere13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行区有正在运行的任务，强行退出有可能会导致采集的数据丢失，是否真的退出Soukey采摘？ 的本地化字符串。
        /// </summary>
        internal static string Quaere14 {
            get {
                return ResourceManager.GetString("Quaere14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择了重置多个已运行的任务，重置任务将恢复任务的初始状态，并删除已经采集的数据，但如果您已经导出了数据或由系统自动导出了数据，则不会收到影响，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere15 {
            get {
                return ResourceManager.GetString("Quaere15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置任务将恢复任务的初始状态，并删除已经采集的数据，但如果您已经导出了数据或由系统自动导出了数据，则不会收到影响，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere16 {
            get {
                return ResourceManager.GetString("Quaere16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您指定导入的任务低于此版本要求，需升级任务后方可进行任务导入，是否现在进行任务升级操作&quot;？ 的本地化字符串。
        /// </summary>
        internal static string Quaere17 {
            get {
                return ResourceManager.GetString("Quaere17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务运行监控文件丢失，请问是否根据正在运行的任务情况自动创建？ 的本地化字符串。
        /// </summary>
        internal static string Quaere18 {
            get {
                return ResourceManager.GetString("Quaere18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成任务索引文件丢失，需要重新建立，但已经完成的任务信息将会丢失，数据内容不会丢失，数据存储在： 的本地化字符串。
        /// </summary>
        internal static string Quaere19 {
            get {
                return ResourceManager.GetString("Quaere19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务信息已经发生了修改，不保存退出？ 的本地化字符串。
        /// </summary>
        internal static string Quaere2 {
            get {
                return ResourceManager.GetString("Quaere2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类下的索引文件丢失，请问是否自动创建？ 的本地化字符串。
        /// </summary>
        internal static string Quaere20 {
            get {
                return ResourceManager.GetString("Quaere20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果此字典内容已被用于网址参数，则网址采集接续会失效，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere21 {
            get {
                return ResourceManager.GetString("Quaere21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果此字典内容已被用于网址参数，则网址采集接续会失效，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere22 {
            get {
                return ResourceManager.GetString("Quaere22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务运行监控文件丢失，请问是否根据正在运行的任务情况自动创建？ 的本地化字符串。
        /// </summary>
        internal static string Quaere3 {
            get {
                return ResourceManager.GetString("Quaere3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您加载的任务与当前系统支持的任务版本不同，请升级任务版本后再进行加载，是否现在进行任务升级操作 的本地化字符串。
        /// </summary>
        internal static string Quaere4 {
            get {
                return ResourceManager.GetString("Quaere4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果此任务正在运行，删除操作不会造成影响，但删除后此任务不可恢复，继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere5 {
            get {
                return ResourceManager.GetString("Quaere5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择删除多个任务，删除操作不会造成影响，但删除后此任务不可恢复，继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere6 {
            get {
                return ResourceManager.GetString("Quaere6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择了清空计划执行历史记录，注意尽管你未全部选中历史记录，但此次操作是指清空所有日志信息，且数据将无法恢复，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere7 {
            get {
                return ResourceManager.GetString("Quaere7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择了删除多个运行区的任务，删除运行区的任务不会影响此任务已经采集完成的数据，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere8 {
            get {
                return ResourceManager.GetString("Quaere8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除运行区的任务不会影响此任务已经采集完成的数据，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string Quaere9 {
            get {
                return ResourceManager.GetString("Quaere9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 递增变量 的本地化字符串。
        /// </summary>
        internal static string rmenu1 {
            get {
                return ResourceManager.GetString("rmenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 递减变量 的本地化字符串。
        /// </summary>
        internal static string rmenu2 {
            get {
                return ResourceManager.GetString("rmenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字母递增 的本地化字符串。
        /// </summary>
        internal static string rmenu3 {
            get {
                return ResourceManager.GetString("rmenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字母递减 的本地化字符串。
        /// </summary>
        internal static string rmenu4 {
            get {
                return ResourceManager.GetString("rmenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POST前缀 的本地化字符串。
        /// </summary>
        internal static string rmenu5 {
            get {
                return ResourceManager.GetString("rmenu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POST后缀 的本地化字符串。
        /// </summary>
        internal static string rmenu6 {
            get {
                return ResourceManager.GetString("rmenu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手工捕获POST数据 的本地化字符串。
        /// </summary>
        internal static string rmenu7 {
            get {
                return ResourceManager.GetString("rmenu7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字典 的本地化字符串。
        /// </summary>
        internal static string rmenu8 {
            get {
                return ResourceManager.GetString("rmenu8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统启动 的本地化字符串。
        /// </summary>
        internal static string SoukeyStartInfo {
            get {
                return ResourceManager.GetString("SoukeyStartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务队列： 的本地化字符串。
        /// </summary>
        internal static string State1 {
            get {
                return ResourceManager.GetString("State1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string State2 {
            get {
                return ResourceManager.GetString("State2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string State3 {
            get {
                return ResourceManager.GetString("State3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string State4 {
            get {
                return ResourceManager.GetString("State4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        internal static string State5 {
            get {
                return ResourceManager.GetString("State5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string State6 {
            get {
                return ResourceManager.GetString("State6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前显示： 的本地化字符串。
        /// </summary>
        internal static string State7 {
            get {
                return ResourceManager.GetString("State7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态：就绪 的本地化字符串。
        /// </summary>
        internal static string State8 {
            get {
                return ResourceManager.GetString("State8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务采集完成 的本地化字符串。
        /// </summary>
        internal static string TaskGCompleted {
            get {
                return ResourceManager.GetString("TaskGCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务采集出错 的本地化字符串。
        /// </summary>
        internal static string TaskGError {
            get {
                return ResourceManager.GetString("TaskGError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务采集失败，已停止 的本地化字符串。
        /// </summary>
        internal static string TaskGFailed {
            get {
                return ResourceManager.GetString("TaskGFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务发布失败，已转入完成区域 的本地化字符串。
        /// </summary>
        internal static string TaskPublishFailed {
            get {
                return ResourceManager.GetString("TaskPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务开始进行数据发布 的本地化字符串。
        /// </summary>
        internal static string TaskPublishing {
            get {
                return ResourceManager.GetString("TaskPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务成功发布 的本地化字符串。
        /// </summary>
        internal static string TaskPulished {
            get {
                return ResourceManager.GetString("TaskPulished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务启动 的本地化字符串。
        /// </summary>
        internal static string TaskStarted {
            get {
                return ResourceManager.GetString("TaskStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务停止 的本地化字符串。
        /// </summary>
        internal static string TaskStoped {
            get {
                return ResourceManager.GetString("TaskStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在运行的任务 的本地化字符串。
        /// </summary>
        internal static string TrayInfo1 {
            get {
                return ResourceManager.GetString("TrayInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在发布的任务 的本地化字符串。
        /// </summary>
        internal static string TrayInfo2 {
            get {
                return ResourceManager.GetString("TrayInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经启动 的本地化字符串。
        /// </summary>
        internal static string TrayInfo3 {
            get {
                return ResourceManager.GetString("TrayInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务启动 的本地化字符串。
        /// </summary>
        internal static string TrayInfo4 {
            get {
                return ResourceManager.GetString("TrayInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘 [免费版] 的本地化字符串。
        /// </summary>
        internal static string TrayTitle {
            get {
                return ResourceManager.GetString("TrayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期日 的本地化字符串。
        /// </summary>
        internal static string W0 {
            get {
                return ResourceManager.GetString("W0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期一 的本地化字符串。
        /// </summary>
        internal static string W1 {
            get {
                return ResourceManager.GetString("W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期二 的本地化字符串。
        /// </summary>
        internal static string W2 {
            get {
                return ResourceManager.GetString("W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期三 的本地化字符串。
        /// </summary>
        internal static string W3 {
            get {
                return ResourceManager.GetString("W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期四 的本地化字符串。
        /// </summary>
        internal static string W4 {
            get {
                return ResourceManager.GetString("W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期五 的本地化字符串。
        /// </summary>
        internal static string W5 {
            get {
                return ResourceManager.GetString("W5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期六 的本地化字符串。
        /// </summary>
        internal static string W6 {
            get {
                return ResourceManager.GetString("W6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每周 的本地化字符串。
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
    }
}
