//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoukeyNetget.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class globalPara {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal globalPara() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoukeyNetget.Resources.globalPara", typeof(globalPara).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MS Access 的本地化字符串。
        /// </summary>
        internal static string DatabaseType1 {
            get {
                return ResourceManager.GetString("DatabaseType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MS Sqlserver 的本地化字符串。
        /// </summary>
        internal static string DatabaseType2 {
            get {
                return ResourceManager.GetString("DatabaseType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MySql 的本地化字符串。
        /// </summary>
        internal static string DatabaseType3 {
            get {
                return ResourceManager.GetString("DatabaseType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不做输出控制 的本地化字符串。
        /// </summary>
        internal static string ExportLimit1 {
            get {
                return ResourceManager.GetString("ExportLimit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出时去掉网页符号 的本地化字符串。
        /// </summary>
        internal static string ExportLimit2 {
            get {
                return ResourceManager.GetString("ExportLimit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出时附加前缀 的本地化字符串。
        /// </summary>
        internal static string ExportLimit3 {
            get {
                return ResourceManager.GetString("ExportLimit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出时附加后缀 的本地化字符串。
        /// </summary>
        internal static string ExportLimit4 {
            get {
                return ResourceManager.GetString("ExportLimit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左起去掉字符 的本地化字符串。
        /// </summary>
        internal static string ExportLimit5 {
            get {
                return ResourceManager.GetString("ExportLimit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右起去掉字符 的本地化字符串。
        /// </summary>
        internal static string ExportLimit6 {
            get {
                return ResourceManager.GetString("ExportLimit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换其中符合条件的字符 的本地化字符串。
        /// </summary>
        internal static string ExportLimit7 {
            get {
                return ResourceManager.GetString("ExportLimit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去掉字符串首尾空格 的本地化字符串。
        /// </summary>
        internal static string ExportLimit8 {
            get {
                return ResourceManager.GetString("ExportLimit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出时采用正则表达式进行替换 的本地化字符串。
        /// </summary>
        internal static string ExportLimit9 {
            get {
                return ResourceManager.GetString("ExportLimit9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string GDataType1 {
            get {
                return ResourceManager.GetString("GDataType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash 的本地化字符串。
        /// </summary>
        internal static string GDataType2 {
            get {
                return ResourceManager.GetString("GDataType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        internal static string GDataType3 {
            get {
                return ResourceManager.GetString("GDataType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        internal static string GDataType4 {
            get {
                return ResourceManager.GetString("GDataType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不做任意格式的限制 的本地化字符串。
        /// </summary>
        internal static string LimitSign1 {
            get {
                return ResourceManager.GetString("LimitSign1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配时去掉网页符号 的本地化字符串。
        /// </summary>
        internal static string LimitSign2 {
            get {
                return ResourceManager.GetString("LimitSign2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只匹配中文 的本地化字符串。
        /// </summary>
        internal static string LimitSign3 {
            get {
                return ResourceManager.GetString("LimitSign3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只匹配双字节字符 的本地化字符串。
        /// </summary>
        internal static string LimitSign4 {
            get {
                return ResourceManager.GetString("LimitSign4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只匹配数字 的本地化字符串。
        /// </summary>
        internal static string LimitSign5 {
            get {
                return ResourceManager.GetString("LimitSign5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只匹配字母数字及常用字符 的本地化字符串。
        /// </summary>
        internal static string LimitSign6 {
            get {
                return ResourceManager.GetString("LimitSign6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义正则匹配表达式 的本地化字符串。
        /// </summary>
        internal static string LimitSign7 {
            get {
                return ResourceManager.GetString("LimitSign7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过指定运行次数计划失效 的本地化字符串。
        /// </summary>
        internal static string PlanDisabledType1 {
            get {
                return ResourceManager.GetString("PlanDisabledType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过指定时间计划失效 的本地化字符串。
        /// </summary>
        internal static string PlanDisabledType2 {
            get {
                return ResourceManager.GetString("PlanDisabledType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        internal static string PlanState1 {
            get {
                return ResourceManager.GetString("PlanState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失效 的本地化字符串。
        /// </summary>
        internal static string PlanState2 {
            get {
                return ResourceManager.GetString("PlanState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期 的本地化字符串。
        /// </summary>
        internal static string PlanState3 {
            get {
                return ResourceManager.GetString("PlanState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不发布数据 的本地化字符串。
        /// </summary>
        internal static string PublishType1 {
            get {
                return ResourceManager.GetString("PublishType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到Access数据库 的本地化字符串。
        /// </summary>
        internal static string PublishType2 {
            get {
                return ResourceManager.GetString("PublishType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到MS Sql Server 的本地化字符串。
        /// </summary>
        internal static string PublishType3 {
            get {
                return ResourceManager.GetString("PublishType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到Excel文件 的本地化字符串。
        /// </summary>
        internal static string PublishType4 {
            get {
                return ResourceManager.GetString("PublishType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到文本文件 的本地化字符串。
        /// </summary>
        internal static string PublishType5 {
            get {
                return ResourceManager.GetString("PublishType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布到MySql数据库 的本地化字符串。
        /// </summary>
        internal static string PublishType6 {
            get {
                return ResourceManager.GetString("PublishType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线发布 的本地化字符串。
        /// </summary>
        internal static string PublishType7 {
            get {
                return ResourceManager.GetString("PublishType7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soukey采摘任务 的本地化字符串。
        /// </summary>
        internal static string RunTaskType1 {
            get {
                return ResourceManager.GetString("RunTaskType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库任务 的本地化字符串。
        /// </summary>
        internal static string RunTaskType2 {
            get {
                return ResourceManager.GetString("RunTaskType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它任务 的本地化字符串。
        /// </summary>
        internal static string RunTaskType3 {
            get {
                return ResourceManager.GetString("RunTaskType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅采集数据 的本地化字符串。
        /// </summary>
        internal static string TaskRunType1 {
            get {
                return ResourceManager.GetString("TaskRunType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集并发布数据 的本地化字符串。
        /// </summary>
        internal static string TaskRunType2 {
            get {
                return ResourceManager.GetString("TaskRunType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据网址采集网页数据 的本地化字符串。
        /// </summary>
        internal static string TaskType1 {
            get {
                return ResourceManager.GetString("TaskType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集整站网页数据 的本地化字符串。
        /// </summary>
        internal static string TaskType2 {
            get {
                return ResourceManager.GetString("TaskType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集RSS聚合数据 的本地化字符串。
        /// </summary>
        internal static string TaskType3 {
            get {
                return ResourceManager.GetString("TaskType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集ajax网页数据 的本地化字符串。
        /// </summary>
        internal static string TaskType4 {
            get {
                return ResourceManager.GetString("TaskType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不编码 的本地化字符串。
        /// </summary>
        internal static string WebCode1 {
            get {
                return ResourceManager.GetString("WebCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string WebCode2 {
            get {
                return ResourceManager.GetString("WebCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gb2312 的本地化字符串。
        /// </summary>
        internal static string WebCode3 {
            get {
                return ResourceManager.GetString("WebCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF-8 的本地化字符串。
        /// </summary>
        internal static string WebCode4 {
            get {
                return ResourceManager.GetString("WebCode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gbk 的本地化字符串。
        /// </summary>
        internal static string WebCode5 {
            get {
                return ResourceManager.GetString("WebCode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 big5 的本地化字符串。
        /// </summary>
        internal static string WebCode6 {
            get {
                return ResourceManager.GetString("WebCode6", resourceCulture);
            }
        }
    }
}
